const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const CREATED = 201;
const AUTH_ERROR = 401;
const CONFLICT_ERROR = 409;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  CREATED,
  AUTH_ERROR,
  CONFLICT_ERROR,
};
